Allow setting custom properties in service_bus send_message()
Azure/azure-sdk-for-rust pull request #1758
Opened 2024-08-19 19:04 UTC by bryanpendleton

Following on the recent broker_properties additions, it'd be nice to be able to set custom properties as well.

2024-08-19 22:09 UTC, heaths requested changes
I wanted to caution again about adding a lot of functionality to the code currently in `main`. It is unsupported, and we will be moving it to a new `legacy` branch soon. I recommend opening tracking issues to make sure you see features in future *supported* crates. I can't guarantee we will review all unsupported crates to migrate functionality to supported crates as we onboard services.

2024-08-23 17:47 UTC, bryanpendleton commented
@microsoft-github-policy-service agree company="Fugu UX"

2024-08-23 17:47 UTC, bryanpendleton commented on sdk/messaging_servicebus/src/service_bus/mod.rs
> +    pub custom_properties: Option<headers::Headers>,
Sure, replaced headers::Headers with just HashMap<String, String>.

2024-08-23 17:50 UTC, bryanpendleton commented
> I wanted to caution again about adding a lot of functionality to the code currently in `main`. It is unsupported, and we will be moving it to a new `legacy` branch soon. I recommend opening tracking issues to make sure you see features in future _supported_ crates. I can't guarantee we will review all unsupported crates to migrate functionality to supported crates as we onboard services.

Thanks for the heads up! Is there a resource someplace documenting this plan, and how best to contribute? I don't know much about the history of these crates besides noting that they were largely originated from Microsoft but marked unofficial.

2024-08-26 21:51 UTC, heaths commented
No, but we'll be making changes soon. If you want to see this change in that source, please open a separate tracking issue and reference this PR for context.

In the future, please push new commits so I can review the diff instead of reviewing the entire PR again.

2024-08-26 21:51 UTC, heaths approved these changes

2024-08-28 21:19 UTC, merged