[page-blob] introduce IfMatch header to put request
Azure/azure-sdk-for-rust pull request #1850
Opened 2024-10-14 12:57 UTC by goksgie

The Azure Docs do not mention, but we can prevent accidental overwrites to Azure Page Blobs when two parties issue a create request. This can be prevented through IfMatch headers, as this commit introduces.

As of today, the only alternative option to prevent overwrite would be managing an internal blob service, or checking whether it exists before issuing a create request (which introduces an additional round-trip).

For C# equivalent, please see: https://github.com/Azure/azure-sdk-for-net/blob/fb0b80d4c8fc99e9e964862f2a374d2bc28096f7/sdk/storage/Azure.Storage.Blobs/src/PageBlobClient.cs#L844

2024-10-14 13:03 UTC, goksgie commented
@microsoft-github-policy-service agree company="Microsoft"

2024-10-14 18:32 UTC, heaths requested changes
The `main` branch is unsupported and should not be used in production. You might want to check if this is already implemented in the `feature/track2` branch or retarget there if not.

2024-10-14 23:19 UTC, goksgie commented
hey @heaths , thanks for quick response. I don't see any code under storage directory in the branch you've suggested. I assume that is still under development.

But, please redirect me otherwise. Thanks!

2024-10-14 23:20 UTC, heaths commented
The storage team is working on a new crate. Keep in mind what's under `main` right now is unsupported.

2024-10-16 23:34 UTC, heaths commented
`main` branch has been moved to `legacy`. Retargeting some old PRs.

2024-10-20 22:19 UTC, goksgie commented
@heaths , would it be possible to merge this to "legacy" branch? We'll possibly use cargo syntax to consume this specific change to simplify the code until we acquire more clarity around official Azure Storage SDK.

2025-02-14 08:34 UTC, closed without merging