Fix BOM handling in queue responses
Azure/azure-sdk-for-rust pull request #309
Opened 2021-06-18 07:55 UTC by arnodb

Hi, this PR fixes the BOM handling in queue API responses.

2021-06-18 18:34 UTC, heaths reviewed
Rather than stripping/skipping the BOM from all responses like this, what about just ignoring the BOM in the response itself? JSON is supposed to be UTF-8, and any different encoding should be reflected in the Content-Encoding header. Doing this centrally would be more productive than having to strip/skip it everywhere it's used.

2021-06-20 16:56 UTC, ctaggart requested changes
There is no need to convert to a `str` to strip a UTF-8 BOM. serde_xml_rs can read directly from a byte slice. I created a `slice_bom` & `read_xml` functions in https://github.com/impero-com/azure-sdk-for-rust/pull/2 to add to this.

2021-06-21 14:33 UTC, arnodb commented
Thanks, that is entirely right.

2021-06-21 15:09 UTC, ctaggart approved these changes

2021-06-21 17:57 UTC, heaths approved these changes

2021-06-22 00:02 UTC, merged