[datalake] Fix path rename operations
Azure/azure-sdk-for-rust pull request #653
Opened 2022-02-05 09:57 UTC by roeap

closes #651

@thovoll - here is the fix for the rename operation, hopefully unblocking you on the delta-rs side :).

To fix the rename operation a few things needed changing:
- header keys for `x-ms-reanme-source` was wrong
- header value for  `x-ms-reanme-source` should be url encoded
- resource query must not be set on rename operation

When writing some tests, I also noticed that parsing the properties header would fail, if no custom properties are set on a file or directory - thus I allowed for an empty (!= missing) property header in the response.

2022-02-06 13:37 UTC, thovoll commented
Thanks @roeap, also for looking deeper and fixing a couple of other issues!

2022-02-06 14:09 UTC, thovoll requested changes
Looks good so far, almost there!

2022-02-06 14:09 UTC, thovoll commented on sdk/storage_datalake/src/request_options.rs
> +        let encoded: String = byte_serialize(self.0.as_bytes()).collect();
Also, maybe add a test that would fail if the URL encoding is missing.

2022-02-08 19:13 UTC, roeap commented on sdk/storage_datalake/examples/file_rename.rs
> +    println!("renamed file properties == {:?}\n", renamed_file_properties);
added some code here - in the tests we already do this in the tests. Also left a comment that this should be replaced by a `exists` function.

2022-02-08 19:21 UTC, roeap commented on sdk/storage_datalake/src/properties.rs
> +        if header_value.is_empty() {
Added a check in the rename test that queries properties on a file with no properties set. This is when this fails.

2022-02-08 19:22 UTC, roeap commented on sdk/storage_datalake/src/request_options.rs
> +        let encoded: String = byte_serialize(self.0.as_bytes()).collect();
I think the rename operation will fail - i.e. source does not get removed - when this is the case.

2022-02-09 04:00 UTC, thovoll approved these changes

2022-02-09 04:01 UTC, merged