Fix 401 Unauthorized error in CosmosDB operations
Azure/azure-sdk-for-rust pull request #832
Opened 2022-06-18 09:07 UTC by spica314

Fix #831

2022-06-19 20:29 UTC, cataggar reviewed
This is fine to me. I'd like @rylev to review. Would prefer a test added. I wonder if the query part is actually needed for the AuthorizationPolicy.

2022-06-19 20:30 UTC, cataggar commented on sdk/data_cosmos/src/authorization_policy.rs
> +        let uri_path = &request.path_and_query()[1..];
This matches what the code was, prior to this change:
https://github.com/Azure/azure-sdk-for-rust/pull/811/files#diff-1d8d32914ddb120499d9acbf8fb856f3757b01bf2d612c4eef44e5ff9590dcbaL57

I think in #811, there was a switch from `http::Uri` to `url::Url` and `path_and_query` existed in the former.

https://docs.rs/http/latest/http/uri/struct.Uri.html#method.path_and_query
https://docs.rs/url/latest/url/struct.Url.html#method.path

2022-06-20 10:33 UTC, rylev requested changes
Whoops! Good find. I think we should probably change the `generate_resource_link` to take a `&Request` and have that function do the magical `&request.path_and_query()[1..]` dance. That way it's all contained within that function and not the callers responsibility to give the `generate_resource_link` function a "uri path" in the right format.

2022-06-20 14:22 UTC, spica314 commented
@rylev 
Thank you for your review!

I moved the code for striping the leading slash to `generate_resource_link`.
(Since my English skill is poor, if my comments are incorrect, please tell me...)

And I also rewrite tests for `generate_resource_links`, but I'm not sure I'm following your suggestion. 
If not, please tell me more (example or functions to use).

2022-06-21 15:54 UTC, rylev approved these changes
Thank you! 🎉

2022-06-21 15:54 UTC, merged